name: "Podcast Generator"
author: "Maher Mansour"
description: "Generate a podcast feed from a directory of audio YAML files"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "blue"
  icon: "mic"
inputs:
  email:
    description: the committer email
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: the committer name
    required: true
    default: ${{ github.actor }}
